In [3]:
import pandas as pd

In [4]:
#data1=pd.read_csv('방탄소년단_남준.csv')
#data2=pd.read_csv('방탄소년단_민윤기.csv')
#data3=pd.read_csv('방탄소년단_뷔.csv')
#data4=pd.read_csv('방탄소년단_정국.csv')
#data5=pd.read_csv('방탄소년단_제이홉.csv')
#data6=pd.read_csv('방탄소년단_지민.csv')
#data7=pd.read_csv('방탄소년단_진.csv')

In [5]:
data1=pd.read_csv('아이돌인스타그램(데이터합치기).csv')
data2=pd.read_csv('블로그크롤링_크리스탈인스타그램.csv')

In [6]:
data1

,Unnamed: 0,time,review,url
0,0,2022. 3. 30. 23:57,"Style news 선미 인스타그램 속 가방, 셋업 코디 패션...",https://blog.naver.com/lovegono/222687454926
1,1,2022. 5. 9. 13:10,지수 드라마 [설강화] 220504 배우 김혜윤 인스타그램에 ...,https://blog.naver.com/syr03051/222723113775
2,2,2022. 2. 16. 14:00,"fashion 제니 화보 패션, 인스타그램 속 캘빈클라인 언더...",https://blog.naver.com/hyperealism/222649161213
3,3,2022. 9. 29. 8:10,"블핑/ 인스타,트위터,SNS 220901 블랙핑크 리사 인스타...",https://blog.naver.com/syr03051/222885506031
4,4,2022. 9. 2. 14:52,BLACKPINK 블랙핑크 지수 인스타그램 사진들 모음 202...,https://blog.naver.com/fenergy12/222864930875
...,...,...,...,...
38347,1445,2022. 9. 12. 0:28,"4) 스드매 정보 4-2. 웨딩드레스 소재, 종류, 체형별, ...",https://blog.naver.com/ej181818/222872352616
38348,1446,2022. 8. 23. 14:22,게시판 [세라(SAERA)] 카리나 인스타그램 속 샌들 패션 ...,https://blog.naver.com/cyyjooo/222855975275
38349,1447,2022. 5. 18. 6:25,"게시판1 블랙핑크 제니, 2개월 연속 걸그룹 개인 브랜드평판 ...",https://blog.naver.com/sy1216_/222736612333
38350,1448,2022. 4. 19. 16:21,스포츠 연예 걸그룹 에스파 미국 코첼라 밸리 뮤직 앤드 아츠 ...,https://blog.naver.com/turbo12177/222705291249
38351,1449,2022. 1. 21. 18:43,연예인 노제 아이키 케미 나못봐서 삐졌어? 인스타그램 댓글 반...,https://blog.naver.com/pkeunyoo/222627892846

In [7]:
data2

,Unnamed: 0,time,review,url
0,0,2022. 6. 3. 12:39,주간뉴스 제 1회 크리스탈케이 페스티벌 그날의 현장으로 고고!...,https://blog.naver.com/soms2565/222757844421
1,1,2022. 9. 28. 22:00,셀럽스타일 폴로 랄프 로렌 ‘폴로 ID’ 미니 숄더 백 : 크...,https://blog.naver.com/rudelulu/222886805489
2,2,2022. 11. 11. 14:03,취향사람 크리스탈 | 크리스탈 사진 모음 | 정수정 사진모음 ...,https://blog.naver.com/222so/222925981865
3,3,2022. 11. 22. 23:47,메종드헤어0403 만수점 만수동미용실 #메종드헤어 #크리스탈 ...,https://blog.naver.com/yellowskys/222935744584
4,4,2022. 6. 21. 16:13,"스타패션 수지, 크리스탈, 아이유, 리아, 안유진, 웬디 패션...",https://blog.naver.com/7822lsy/222782606400
...,...,...,...,...
229,229,2022. 3. 13. 21:42,정보 웰리카 크리스탈 콜라겐 비오틴까지 챙긴 기능성 콜라겐 ...,https://blog.naver.com/meinjess/222671625483
230,230,2022. 6. 13. 1:22,SHOPPING 키라키라! 핫한 인스타그램 셀럽백 KAR...,https://blog.naver.com/reeie80/222770518097
231,231,2022. 3. 6. 12:58,리뷰 크리스탈 문진 2만원대 선물 추천 #마이시리즈 ...,https://blog.naver.com/poooo_rin/222665188415
232,232,2022. 9. 26. 18:00,"Celeb N Style 크리스탈, 김도연, 김민주, 이...",https://blog.naver.com/99551414/222884824810
233,233,2022. 4. 27. 3:06,사랑해나 [송파/강동]디어크리스탈 혼주 메이크업 솔직 찐후기 ...,https://blog.naver.com/haenah0701/222712776681

In [8]:
data1
del data1['Unnamed: 0']
data1.head()

,time,review,url
0,2022. 3. 30. 23:57,"Style news 선미 인스타그램 속 가방, 셋업 코디 패션...",https://blog.naver.com/lovegono/222687454926
1,2022. 5. 9. 13:10,지수 드라마 [설강화] 220504 배우 김혜윤 인스타그램에 ...,https://blog.naver.com/syr03051/222723113775
2,2022. 2. 16. 14:00,"fashion 제니 화보 패션, 인스타그램 속 캘빈클라인 언더...",https://blog.naver.com/hyperealism/222649161213
3,2022. 9. 29. 8:10,"블핑/ 인스타,트위터,SNS 220901 블랙핑크 리사 인스타...",https://blog.naver.com/syr03051/222885506031
4,2022. 9. 2. 14:52,BLACKPINK 블랙핑크 지수 인스타그램 사진들 모음 202...,https://blog.naver.com/fenergy12/222864930875

In [9]:
data2
del data2['Unnamed: 0']
#data2.rename(columns={'review':'doc'}, inplace=True)
data2.head()

,time,review,url
0,2022. 6. 3. 12:39,주간뉴스 제 1회 크리스탈케이 페스티벌 그날의 현장으로 고고!...,https://blog.naver.com/soms2565/222757844421
1,2022. 9. 28. 22:00,셀럽스타일 폴로 랄프 로렌 ‘폴로 ID’ 미니 숄더 백 : 크...,https://blog.naver.com/rudelulu/222886805489
2,2022. 11. 11. 14:03,취향사람 크리스탈 | 크리스탈 사진 모음 | 정수정 사진모음 ...,https://blog.naver.com/222so/222925981865
3,2022. 11. 22. 23:47,메종드헤어0403 만수점 만수동미용실 #메종드헤어 #크리스탈 ...,https://blog.naver.com/yellowskys/222935744584
4,2022. 6. 21. 16:13,"스타패션 수지, 크리스탈, 아이유, 리아, 안유진, 웬디 패션...",https://blog.naver.com/7822lsy/222782606400

In [10]:
df=pd.concat([data1, data2], axis = 0)
#del df['Unnamed: 0']
df.head()

,time,review,url
0,2022. 3. 30. 23:57,"Style news 선미 인스타그램 속 가방, 셋업 코디 패션...",https://blog.naver.com/lovegono/222687454926
1,2022. 5. 9. 13:10,지수 드라마 [설강화] 220504 배우 김혜윤 인스타그램에 ...,https://blog.naver.com/syr03051/222723113775
2,2022. 2. 16. 14:00,"fashion 제니 화보 패션, 인스타그램 속 캘빈클라인 언더...",https://blog.naver.com/hyperealism/222649161213
3,2022. 9. 29. 8:10,"블핑/ 인스타,트위터,SNS 220901 블랙핑크 리사 인스타...",https://blog.naver.com/syr03051/222885506031
4,2022. 9. 2. 14:52,BLACKPINK 블랙핑크 지수 인스타그램 사진들 모음 202...,https://blog.naver.com/fenergy12/222864930875

In [11]:
#del df['Unnamed: 0']
#df

In [12]:
#중복행 제거
#df.drop_duplicates(inplace=True)

In [13]:
len(df)

38586

In [14]:
df.to_csv('아이돌인스타그램(데이터합치기).csv', encoding='utf-8-sig')